package com.example.amqp.topology.mapping;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Build-time marker: this type is a code-first event contract whose JSON Schema should be
 * generated by {@code schema-gen-tools} at {@code process-classes}. Nested value objects, enums,
 * and topology auto-configurations must not carry this annotation.
 *
 * <p>Discovered by package scan (not by hand-listed FQCNs in the contracts POM). Retention is
 * {@link RetentionPolicy#RUNTIME} so the scanner can see it after {@code Class.forName}.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface GenerateSchema {}
